### ISSUE TITLE
activation error

### ISSUE THREAD

**Issue by kochler** [budgetneon/v2pagecache#10]
Hi!

After installation when I want to edit the V2 Page Cache get this:

"Fatal error: Can't use method return value in write context in ...system/library/v2pagecache.php on line 249"

I installed the last version v2pagecache-1.1.4.ocmod.zip and my version of OpenCart is 2.2.0.0

Can you help me?
Thank you

**Comment by budgetneon** [comment]
Try newer version 1.1.5

**Comment by kochler** [comment]
Thank you.
The "Fatal error: Can't use method return value in write context in ...system/library/v2pagecache.php on line 249" error is solved but still don't working.

After I press the "Edit" button I receive at "Status" this message: "ERROR (Cannot find bottom marker in index.php) "
 Compatibility:
Component   Detected    Status
PHP 5.4.34  supported (PHP 5.4 or greater)
SAPI    litespeed   supported (we work around broken http_response_code() in litespeed)

And here a "Wait..." button.  

Please help me
Thanks

**Comment by kochler** [comment]
Thank you.
The "Fatal error: Can't use method return value in write context in
...system/library/v2pagecache.php on line 249" error is solved but still
don't working.

After I press the "Edit" button I receive at "Status" this message: "ERROR
(Cannot find bottom marker in index.php) "
Compatibility:
Component Detected Status
PHP 5.4.34 supported (PHP 5.4 or greater)
SAPI litespeed supported (we work around broken http_response_code() in
litespeed)

And here a "Wait..." button.

Please help me
Thanks

2016-08-25 14:39 GMT+03:00 Budget Neon notifications@github.com:

**Comment by budgetneon** [comment]
You would have to install manually then. 

See:  https://github.com/budgetneon/v2pagecache#manual-installation

**Comment by kochler** [comment]
Hi,

I follow the manual installation steps ( meen I added the line codes) but
still have this problem.

After I press the "Edit" button I receive at "Status" this message: "ERROR
(Cannot find bottom marker in index.php) "

Compatibility:
Component Detected Status
PHP 5.4.34 supported (PHP 5.4 or greater)
SAPI litespeed supported (we work around broken http_response_code() in
litespeed)
And here a "Wait..." button

Can you help me with another ideea?

Thank you

2016-08-30 17:43 GMT+03:00 Budget Neon notifications@github.com:

**Comment by kgudzinski** [comment]
Hello, i have the same problem and after manual installation (OC v 2.2.0.0).

**Comment by GoldenScrew** [comment]
I installed it, but when I try activate module, I have the alert with text:
"error
undefined
"
How I can delete this module now? :(

**Comment by budgetneon** [comment]
You uninstall the module just like any other module...from the admin panel

https://isenselabs.com/posts/how-to-install-or-delete-modules-in-opencart-20
