### ISSUE TITLE
Error on the configuration page

### ISSUE THREAD

**Issue by NazikTV** [budgetneon/v2pagecache#14]
In the admin panel on the configuration page, I see the error:
Notice: Undefined index: default in /home/u411192975/public_html/system/library/v2pagecache.php on line 107Warning: array_key_exists() expects parameter 2 to be array, null given in /home/u411192975/public_html/system/library/v2pagecache.php on line 64Warning: array_key_exists() expects parameter 2 to be array, null given in /home/u411192975/public_html/system/library/v2pagecache.php on line 71Notice: Undefined index: default in /home/u411192975/public_html/system/library/v2pagecache.php on line 107

Module version is 1.1.5. Open cart version is 2.3.0.2, PHP 5.6 .21. And also page constantly reloading with the message "admin session expired? reloading page".

**Comment by budgetneon** [comment]
Sorry, we're not able to help.  This module worked well with earlier versions of opencart, but opencart made many changes to session handling, layout of the index.php file, and so forth.

See https://github.com/budgetneon/v2pagecache#important-note
