### ISSUE TITLE
Admin Session Expired? Reloading Page

### ISSUE THREAD

**Issue by emicrone** [budgetneon/v2pagecache#15]
Hey, 
Thank you very much for this extension, i installed as you mention in your manual for my Store OC 2.3.0.2, And i add the Index.php codes
BUT when i installed the extension and tried to use it, it give me a JS Alert popup, tellin me that "**ADMIN SESSION EXPIRED. Reloading page**"   (_SEE Capture.jpg_)
And in the header i see some warning "Notice : Undefined index : default in ...system/library/v2pagecache.php . . . .   (You can see the whole Warning and notice in the capture img)

Even when i click on OK , it reload the page and give same Alert again and again.
I Tried to delete my cache, playing with session timout . . . desactivating all my VQMOD, Desactivate some major extension but sme issue i got each time.

Plz help 

Thank you very much
![capture](https://cloud.githubusercontent.com/assets/2669969/19011196/c7c05e32-8786-11e6-952f-eaa35931161f.jpg)

**Comment by budgetneon** [comment]
Try the latest version, 1.1.6, I made a ton of changes to account for opencart changes that break the page cache.

**Comment by emicrone** [comment]
Thank you very much it work with the last version 1.1.8, very good extension, 5 STARS \* \* \* \* \*

**Comment by budgetneon** [comment]
Good news...closing issue.
