### ISSUE TITLE
Warning array_key_exists()

### ISSUE THREAD

**Issue by css-coder** [budgetneon/v2pagecache#16]
Hi) on my website only Russian language and the only currency the ruble. When the module is an error. How to fix? Thank you!
![a4370-clip-26kb](https://cloud.githubusercontent.com/assets/12234195/19020038/1b987376-88a6-11e6-8085-bcf03e4d9b90.jpg)

**Comment by budgetneon** [comment]
Try the latest version, 1.1.6, I made a ton of changes to account for opencart changes that break the page cache.
