### ISSUE TITLE
500 with cachebydevice on - NGINX fastcgi

### ISSUE THREAD

**Issue by romankk** [budgetneon/v2pagecache#20]
Hi,
Clean install CentOS 7 with centminmod php7 and Opencart 2.3 and latest Journal (nothing else)
I'm getting 500 if I turn cachebydevice on. Without Journal and with cachebydevice off, everething cache is working.
In server log I see following:
2016/10/20 18:49:46 [error] 4280#4280: _164 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare V2PageCache::$cachebydevice in /usr/local/nginx/html/system/library/v2pagecache.php on line 36" while reading response header from upstream, client: 31.130.147._**, server: mysite.com, request: "GET /admin/index.php?route=extension/module/v2pagecache&token=snnpf6cDnDOOZSIDWW70AejydEG3MCBQ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "91.107.108.***"

**Comment by budgetneon** [comment]
Note the comment in the source:

```
// make sure only one of the three lines below is uncommented
```

Likely that you've got more than one of them uncommented.

Also, the Journal theme has it's own pagecache.  I don't recommend using our pagecache with the Journal theme, as they can clash.

**Comment by romankk** [comment]
You are 100% correct!
 I had both on:
private $cachebydevice=false;
private $cachebydevice='mobiledetect';

Once I changed to 
//private $cachebydevice=false;
    private $cachebydevice='mobiledetect';

Everything is working.
Thank you!
