### ISSUE TITLE
Session Error OC 2.3.0.2

### ISSUE THREAD

**Issue by arigato-one** [budgetneon/v2pagecache#23]
OC 2.3.0.2, PHP 7.1 
Fatal error: SessionHandler::create_sid(): Cannot call default session handler in Unknown on line 0

**Comment by budgetneon** [comment]
You can see a similar issue here: https://github.com/budgetneon/v2pagecache/issues/21

And what he did to fix it: https://github.com/budgetneon/v2pagecache/pull/22/files

I don't plan on rolling this into the main code, as I don't encounter this error, and I have haven't tested this pull request.  

It's a bit of an odd fix, as while it calls the OC session handling, it doesn't explicitly create the session.  So, while it may make the error go away, I'm not 100% sure it's a good fix.  If it doesn't create a session, caching won't work right.

**Comment by arigato-one** [comment]
I applied that fix. 
It’s ok now. 
You wish to have access to my dev site so that you can take a look? 
Thanks

**Comment by budgetneon** [comment]
No, that's okay.   Before I make that change, I would have to test all of
the various 2.x releases....Opencart made a lot of changes to session
handling over those releases.

So, while it seems to work for you, it may not work for OC 2.0.1, etc.

Thank you
