### ISSUE TITLE
if add to cart items dosn't work all webpages with v2cache.

### ISSUE THREAD

**Issue by tunnabulutlu** [budgetneon/v2pagecache#24]
2.0.3.1 opencart
journal 2 (all enable journal cache)

add to cart 1 item after search webpage bat very slow 10x slow :(
remove cart after again v2cache works perfect!

please help me ?

I try all journal theme and default opencart.all module and extentions disable.
thank you

**Comment by budgetneon** [comment]
That's how all page caches work.   You can't serve a cached page to someone who has an item in their cart.   The cart contents, price total, etc, are part of the page.

**Comment by tunnabulutlu** [comment]
thank you but I 've Tried lightning module and It was great.no problem after add to cart search webpage.
There is no minimum speed loss with lightning.I thought it might be...
(I've tried nitropack moudle last and all version very bad dosn'! work and same problem.)

I will be very happy if you have an idea .

tahnk you for repyl

**Comment by budgetneon** [comment]
>I 've Tried lightning module and It was great

It's not a page cache then.  It's accelerating using some other techniques.

A page cache is exactly what it sounds like...it caches a page.   If the page has per-customer data (like things in the cart), it can't be cached.

**Comment by tunnabulutlu** [comment]
Thank you very much for your prompt reply and your help.

**Comment by maplewang** [comment]
So can the page use Ajax to get customer cart from website? I mean install an Ajax cart to serve it?

**Comment by budgetneon** [comment]
No, not without a lot of other work.   There's the login area that displays a name for logged in users, session cookies, the "compare products" functionality, etc.   In theory, you could ajaxify all things user-specific and have them in a separate cookie domain, then alter the page cache code.   But, we're not going to do anything like that.
