### ISSUE TITLE
mega filter pro dosn't work

### ISSUE THREAD

**Issue by tunnabulutlu** [budgetneon/v2pagecache#25]
mega filter pro
journal
oc  2.0.3.1

disable v2pagecache after check no problem.
enable v2pagecache after check dosn't work :(

can you help me ?  

I 've Tried off or on cache megafilter in megafilter setting disable or enable.

**Comment by budgetneon** [comment]
It's a similar problem to the one you opened earlier.

Megafilter creates different types of content for the same url.   That won't work for a page cache.

If it did something like http://example.com/category?filter1=x&filter2=y , then it would work, as there would only be one "page" that went with each url.   Unfortunately, mega filter doesn't work that way.

**Comment by tunnabulutlu** [comment]
v2pagecache ,Skip megafilter module.Would it be?

thank you

**Comment by budgetneon** [comment]
There's no easy fix.   Skip only skips by url.

**Comment by tunnabulutlu** [comment]
skip to mega filter for home page will be ?  (I do not think so)

or

home page url skip  '#/#',  What should i write ? thank you

**Comment by budgetneon** [comment]
'#^/$#' would skip the home page.

It's a regular expression 

https://en.wikipedia.org/wiki/Regular_expression

**Comment by tunnabulutlu** [comment]
skipped home page successful. but Did not work again mega filter for home page :(

I could not do it :)

**Comment by tunnabulutlu** [comment]
Everyone uses filter.Will not you have a solution to that?
skip megafilter or skip home page.I try skip home page but doesn't work still megafilter on home page.

and have mobil other problems..

**Comment by budgetneon** [comment]
No, I'm not going to buy a paid extension to support an extension that I give away at no cost.

There are page cache modules that you can pay for.   Those perhaps have more extensive support than I can offer.  Or, you could try the page cache that already comes with the Journal theme that you paid for.

**Comment by budgetneon** [comment]
Also, see this https://github.com/budgetneon/v2pagecache/issues/7

**Comment by tunnabulutlu** [comment]
ı Try all cache nitropact and orher all error other modules :(

thank you

**Comment by adrianmihalko** [comment]
Mega Filter Plus adds /mfp/ to the URL so you can skip cache for these pages.
