### ISSUE TITLE
problem sidebar

### ISSUE THREAD

**Issue by tunnabulutlu** [budgetneon/v2pagecache#26]
1-journal sidebar (right)problem home page
2-oc sidebar problem (left)
3-home page same prodcuts no see ( interesting..

sametimes no seen :(

2.0.3.1

**Comment by budgetneon** [comment]
I can't really help without detailed, technical descriptions of the issue, specific errors from the log, and so forth.

That said, the Journal theme already has it's own page cache, so perhaps you should use that instead.

Our page cache does work fine with the default theme that comes with opencart.

**Comment by tunnabulutlu** [comment]
thank you very fast support and free.

thank you :)


and others prbolem other modules can you help me :(( please :(

I need this file but for oc 2 :)
https://gist.github.com/weismannweb/a16b5d103e89ca1d1209
I try my chance :)

**Comment by budgetneon** [comment]
We're a neon sign shop...not generally opencart developers.

**Comment by tunnabulutlu** [comment]
Thank you for reply
