### ISSUE TITLE
php-fpm is not supported at the moment

### ISSUE THREAD

**Issue by vt887** [budgetneon/v2pagecache#28]
Hi there,

Could you add php-fpm support to your code?

Thanks.

**Comment by budgetneon** [comment]
Have you tried it?  Can you describe what you saw?

**Comment by maplewang** [comment]
PHP 7.0.18-0ubuntu0.16.04.1
 SAPI fpm-fcgi
unsupported (pagecache has not been tested with this SAPI)

nginx Ubuntu 16.04

**Comment by budgetneon** [comment]
I'm asking if you found something that didn't work.

The words "unsupported" mean that we haven't tested it, not that it doesn't work.

**Comment by maplewang** [comment]
It shows.
Cached Files  Total
Valid               8
Expired           99
so I think it should work, only the warn.

**Comment by budgetneon** [comment]
Okay.  I have no plans to officially test with fpm.   If it's working for you, that's great.
