### ISSUE TITLE
some quenstion on journal theme?

### ISSUE THREAD

**Issue by ayttk** [budgetneon/v2pagecache#29]
Hi
I am trying install on my opencart 2.3.0.2 
v2pagecache-oc23-1.3.ocmod
disable journal cache.

but i have some problem with that .
can you give me some adivce?

MY HOST INFORMATION AS BELOW

![2017-09-21_112140](https://user-images.githubusercontent.com/23657624/30677606-3bb6d4b0-9ebf-11e7-8de9-fc68ffea2eca.png)

but its can not load the theme correctly.

how can i fix that ? can you give me some adivce?

http://104.199.252.15/

thank you.

**Comment by budgetneon** [comment]
f you have the Journal theme, it has it's own built-in page cache, so there's not much benefit trying to get ours to work with it.

**Comment by budgetneon** [comment]
If you have the Journal theme, it has it's own built-in page cache, so
there's not much benefit trying to get ours to work with it.

Thank you

Kerry
