### ISSUE TITLE
ERROR status in admin panel

### ISSUE THREAD

**Issue by jchkau** [budgetneon/v2pagecache#6]
Hi, I'm testing opencart 2.2.0.0 with wampserver, after the installation, which show ERROR status in admin panel. And I need to add the following code and create an empty folder manually(from your instruction) to make it work, and I now cannont disable the cache, could you tell me what problems?  (php ver.5.6.15, mysql5.7.9, apache 2.4.17)   Thx, anyway.
"if ($pagecache->OkToCache()) { 
$pagecache->CachePage($response); 
} "

**Comment by budgetneon** [comment]
It probably means that the user you are running the webserver as does not have rights to write to the index.php file.

Also, the instructions don't say anything about an "empty folder", and the code that needs to be added is more than what you listed there.  The manual instructions are here: https://github.com/budgetneon/v2pagecache#manual-installation
